# Generated by Django 2.2 on 2021-10-11 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20211011_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogentry',
            name='publishDate',
        ),
    ]
