# Generated by Django 2.2 on 2021-10-11 14:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_blogentry_publishdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogentry',
            name='publishDate',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
