# Generated by Django 2.2 on 2021-10-26 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20211025_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogentry',
            name='blogBody',
            field=models.TextField(max_length=10000, verbose_name='Body Text'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='commBody',
            field=models.CharField(max_length=10000, verbose_name='Comment'),
        ),
    ]
